DROP TABLE IF EXISTS `faction`;

CREATE TABLE `faction` (
  `entry` mediumint(8) NOT NULL,
  `name` text,
  `description` text,
  PRIMARY KEY (`entry`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `faction`(`entry`, `name`, `description`) VALUES 
(1, 'PLAYER, Human', ''),
(2, 'PLAYER, Orc', ''),
(3, 'PLAYER, Dwarf', ''),
(4, 'PLAYER, Night Elf', ''),
(5, 'PLAYER, Undead', ''),
(6, 'PLAYER, Tauren ', ''),
(7, 'Creature', ''),
(8, 'PLAYER, Gnome', ''),
(9, 'PLAYER, Troll', ''),
(14, 'Monster', ''),
(15, 'Defias Brotherhood', ''),
(16, 'Gnoll - Riverpaw', ''),
(17, 'Gnoll - Redridge', ''),
(18, 'Gnoll - Shadowhide', ''),
(19, 'Murloc', ''),
(20, 'Undead, Scourge', ''),
(21, 'Booty Bay', 'This booming coastal city is run by Baron Revilgaz of the Blackwater Raiders.  Mortal enemies of the Bloodsail Buccaneers and part of the Steamwheedle Cartel.'),
(22, 'Beast - Spider', ''),
(23, 'Beast - Boar', ''),
(24, 'Worgen', ''),
(25, 'Kobold', ''),
(26, 'Troll, Bloodscalp', ''),
(27, 'Troll, Skullsplitter', ''),
(28, 'Prey', ''),
(29, 'Beast - Wolf', ''),
(30, 'Defias Brotherhood Traitor', ''),
(31, 'Friendly', ''),
(32, 'Trogg', ''),
(33, 'Troll, Frostmane', ''),
(34, 'Orc, Blackrock', ''),
(35, 'Villian', ''),
(36, 'Victim', ''),
(37, 'Beast - Bear', ''),
(38, 'Ogre', ''),
(39, 'Kurzen\'s Mercenaries', ''),
(40, 'Escortee', ''),
(41, 'Venture Company', ''),
(42, 'Beast - Raptor', ''),
(43, 'Basilisk', ''),
(44, 'Dragonflight, Green', ''),
(45, 'Lost Ones', ''),
(46, ' Blacksmithing - Armorsmithing', ''),
(47, 'Ironforge', 'This Alliance capital is the pride of the Dun Morogh dwarves.  Home to King Magni.'),
(48, 'Dark Iron Dwarves', ''),
(49, 'Human, Night Watch', ''),
(50, 'Dragonflight, Red', ''),
(51, 'Gnoll - Mosshide', ''),
(52, 'Orc, Dragonmaw', ''),
(53, 'Gnome - Leper', ''),
(54, 'Gnomeregan Exiles', 'The former denizens of Gnomeregan, now living in exile in Ironforge and in league with the Alliance.'),
(55, 'Leopard', ''),
(56, 'Scarlet Crusade', ''),
(57, 'Gnoll - Rothide', ''),
(58, 'Beast - Gorilla', ''),
(59, 'Thorium Brotherhood', 'The dwarves of the Thorium Brotherhood epitomize excellence in craftsmanship and are bent on unlocking the secrets of Blackrock Mountain.'),
(60, 'Naga', ''),
(61, 'Dalaran', ''),
(62, 'Forlorn Spirit', ''),
(63, 'Darkhowl', ''),
(64, 'Grell', ''),
(65, 'Furbolg', ''),
(66, 'Horde Generic', ''),
(67, 'Horde', ''),
(68, 'Undercity', 'Led by Sylvanas Windrunner, the Forsaken have joined a tenuous alliance with the Horde and established this capital in the vast depths under the Ruins of Lordaeron.'),
(69, 'Darnassus', 'The Alliance capital is populated by Night Elves and is located in the island of Teldrassil.  Ruled by the Priestess of the Moon, Tyrande Whisperwind.'),
(70, 'Syndicate', 'A primarily human criminal organization that operates mostly out of the Alterac Mountains and Hillsbrad Foothills.'),
(71, 'Hillsbrad Militia', ''),
(72, 'Stormwind', 'One of the last bastions of human power, this Alliance capital is ruled by the child king, Anduin Wrynn.'),
(73, 'Demon', ''),
(74, 'Elemental', ''),
(75, 'Spirit', ''),
(76, 'Orgrimmar', 'Founded by Thrall, this Horde capital city is home to many of the proud orc clans of Durotar.'),
(77, 'Treasure', ''),
(78, 'Gnoll - Mudsnout', ''),
(79, 'HIllsbrad, Southshore Mayor', ''),
(80, 'Dragonflight, Black', ''),
(81, 'Thunder Bluff', 'Cairne Bloodhoof leads his people, the Proud Tauren, from this mighty Horde capital.'),
(82, 'Troll, Witherbark', ''),
(83, ' Leatherworking - Elemental', ''),
(84, 'Quilboar, Razormane', ''),
(85, 'Quilboar, Bristleback', ''),
(86, ' Leatherworking - Dragonscale', ''),
(87, 'Bloodsail Buccaneers', 'These bloodthirsty corsairs are the bane of many a merchant in the high seas.  Sworn enemies of Booty Bay.'),
(88, 'Blackfathom', ''),
(89, 'Makrura', ''),
(90, 'Centaur, Kolkar', ''),
(91, 'Centaur, Galak', ''),
(92, 'Gelkis Clan Centaur', 'These centaur have made their home in the southern region of Desolace.  Mortal enemies of the Magram Centaur.'),
(93, 'Magram Clan Centaur', 'These centaur have made their home in the eastern region of Desolace.  Mortal enemies of the Gelkis Centaur.'),
(94, 'Maraudine', ''),
(108, 'Theramore', ''),
(109, 'Quilboar, Razorfen', ''),
(110, 'Quilboar, Razormane 2', ''),
(111, 'Quilboar, Deathshead', ''),
(128, 'Enemy', ''),
(148, 'Ambient', ''),
(168, 'Nethergarde Caravan', ''),
(169, 'Steamwheedle Cartel', ''),
(189, 'Alliance Generic', ''),
(209, 'Nethergarde', ''),
(229, 'Wailing Caverns', ''),
(249, 'Silithid', ''),
(269, 'Silvermoon Remnant', ''),
(270, 'Zandalar Tribe', 'These trolls have come to Yojamba Isle in an effort to recruit help against the resurrected Blood God and his Atal\'ai Priests in Zul\'Gurub.'),
(289, ' Blacksmithing - Weaponsmithing', ''),
(309, 'Scorpid', ''),
(310, 'Beast - Bat', ''),
(311, 'Titan', ''),
(329, 'Taskmaster Fizzule', ''),
(349, 'Ravenholdt', 'This guild of thieves and assassins welcomes only those of extraordinary prowess into its fold.  Sworn rivals of the Syndicate.'),
(369, 'Gadgetzan', 'Capital of the Steamwheedle Cartel and home to goblinhood\'s finest engineers, alchemists and merchants.'),
(389, 'Gnomeregan Bug', ''),
(409, 'Harpy', ''),
(429, 'Burning Blade', ''),
(449, 'Shadowsilk Poacher', ''),
(450, 'Searing Spider', ''),
(469, 'Alliance', ''),
(470, 'Ratchet', 'Part of the Steamwheedle Cartel, this goblin city provides a neutral haven for those that wish to trade goods and services in the Barrens.'),
(471, 'Wildhammer Clan', 'Though not a part of the Alliance, the dwarves of Aerie Peak have opened their doors to it and hold the Horde as enemies.'),
(489, 'Goblin, Dark Iron Bar Patron', ''),
(509, 'The League of Arathor', 'The League of Arathor seeks to reclaim lost land of Arathi Basin for their benefactors in Stormwind.'),
(510, 'The Defilers', 'The Defilers seek to claim Arathi Basin\'s valuable resources for the Horde.'),
(511, 'Giant', ''),
(529, 'Argent Dawn', 'An organization focused on protecting Azeroth from the threat of the Scourge.  Strongholds of the Argent Dawn can be found in the Eastern and Western Plaguelands.'),
(530, 'Darkspear Trolls', 'This tribe of exiled trolls has joined forces with Thrall and the Horde.  They now call Durotar their home, which they share with their orc allies.'),
(531, 'Dragonflight, Bronze', ''),
(532, 'Dragonflight, Blue', ''),
(549, ' Leatherworking - Tribal', ''),
(550, ' Engineering - Goblin', ''),
(551, ' Engineering - Gnome', ''),
(569, ' Blacksmithing - Hammersmithing', ''),
(570, ' Blacksmithing - Axesmithing', ''),
(571, ' Blacksmithing - Swordsmithing', ''),
(572, 'Troll, Vilebranch', ''),
(573, 'Southsea Freebooters', ''),
(574, 'Caer Darrow', ''),
(575, 'Furbolg, Uncorrupted', ''),
(576, 'Timbermaw Hold', 'As the last uncorrupted furbolg tribe, the Timbermaw seek to preserve their spiritual ways and end the suffering of their brethren.'),
(577, 'Everlook', 'This trading post is run by the goblins of the Steamwheedle Cartel and it sits in the crossroads of Winterspring\'s main trade routes.'),
(589, 'Wintersaber Trainers', 'This small group of reclusive night elves raises and trains wintersabers in the Winterspring area.'),
(609, 'Cenarion Circle', 'The druids of Cenarion Circle are guardians of nature and make their home in tranquil Moonglade.'),
(629, 'Shatterspear Trolls', ''),
(630, 'Ravasaur Trainers', ''),
(649, 'Majordomo Executus', ''),
(669, 'Beast - Carrion Bird', ''),
(670, 'Beast - Cat', ''),
(671, 'Beast - Crab', ''),
(672, 'Beast - Crocilisk', ''),
(673, 'Beast - Hyena', ''),
(674, 'Beast - Owl', ''),
(675, 'Beast - Scorpid', ''),
(676, 'Beast - Tallstrider', ''),
(677, 'Beast - Turtle', ''),
(678, 'Beast - Wind Serpent', ''),
(679, 'Training Dummy', ''),
(689, 'Dragonflight, Black - Bait', ''),
(709, 'Battleground Neutral', ''),
(729, 'Frostwolf Clan', 'The Frostwolf Clan seeks to drive out the dwarves of the Stormpike Expedition from Alterac Valley.'),
(730, 'Stormpike Guard', 'The Stormpike Dwarves have set up residence in Alterac Valley, where they\'re locked in battle with the Frostwolf Orcs.'),
(749, 'Hydraxian Waterlords', 'These elementals have made their home on the islands east of Azshara.  Sworn enemies of the armies of Ragnaros.'),
(750, 'Sulfuron Firelords', ''),
(769, 'Gizlock\'s Dummy', ''),
(770, 'Gizlock\'s Charm', ''),
(771, 'Gizlock', ''),
(789, 'Moro\'gai', ''),
(790, 'Spirit Guide - Alliance', ''),
(809, 'Shen\'dralar', 'A remnant of the once powerful elves living in Dire Maul, yet still wise and knowledgeable about great secrets. '),
(829, 'Ogre (Captain Kromcrush)', ''),
(849, 'Spirit Guide - Horde', ''),
(869, 'Jaedenar', ''),
(889, 'Warsong Outriders', 'Fierce orcs of the Warsong Clan, locked in battle against the Silverwing Sentinels in Warsong Gulch.'),
(890, 'Silverwing Sentinels', 'Staunch defenders of Ashenvale, locked in battle against the Warsong Outriders in Warsong Gulch.'),
(891, 'Alliance Forces', ''),
(892, 'Horde Forces', ''),
(893, 'Revantusk Trolls', ''),
(909, 'Darkmoon Faire', 'A traveling fair that showcases the weird and the extraordinary.  Often spotted in Elwynn Forest and Mulgore.'),
(910, 'Brood of Nozdormu', 'The descendants of the Bronze Dragonflight are the guardians of time and care little for the mortal races.'),
(912, 'Might of Kalimdor', ''),
(915, 'Armies of C\'Thun', ''),
(916, 'Silithid Attackers', ''),
(917, 'The Ironforge Brigade', ''),
(918, 'RC Enemies', ''),
(919, 'RC Objects', ''),
(920, 'Red', ''),
(921, 'Blue', ''),
(928, 'Scourge Invaders', ''),
(931, 'Test Faction (not a real faction)', 'This faction only exists to test the editing of faction names and descriptions...'),
(950, 'ToWoW - Flag', ''),
(951, 'ToWoW - Flag Trigger Alliance (DND)', ''),
(954, 'ToWoW - Flag Trigger Horde (DND)', '');