DROP TABLE IF EXISTS `itemsubclass`;

CREATE TABLE `itemsubclass` (
  `itemclassid` mediumint(8) NOT NULL,
  `subclassid` mediumint(8) NOT NULL,
  `displayname` text,
  `verbosename` text,
  PRIMARY KEY (`itemclassid`, `subclassid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `itemsubclass`(`itemclassid`, `subclassid`, `displayname`, `verbosename`) VALUES 
(-1, -1, 'NewItem', ''),
(0, 0, 'Consumable', ''),
(0, 1, 'Cheese/Bread(OBSOLETE)', ''),
(0, 2, 'Liquid(OBSOLETE)', ''),
(1, 0, 'Bag', ''),
(1, 1, 'Soul Bag', ''),
(1, 2, 'Herb Bag', ''),
(1, 3, 'Enchanting Bag', ''),
(1, 4, 'Engineering Bag', ''),
(2, 0, 'Axe', 'One-Handed Axes'),
(2, 1, 'Axe', 'Two-Handed Axes'),
(2, 2, 'Bow', 'Bows'),
(2, 3, 'Gun', 'Guns'),
(2, 4, 'Mace', 'One-Handed Maces'),
(2, 5, 'Mace', 'Two-Handed Maces'),
(2, 6, 'Polearm', 'Polearms'),
(2, 7, 'Sword', 'One-Handed Swords'),
(2, 8, 'Sword', 'Two-Handed Swords'),
(2, 9, 'Obsolete', ''),
(2, 10, 'Staff', 'Staves'),
(2, 11, 'Exotic', 'One-Handed Exotics'),
(2, 12, 'Exotic', 'Two-Handed Exotics'),
(2, 13, 'Fist Weapon', 'Fist Weapons'),
(2, 14, 'Miscellaneous', ''),
(2, 15, 'Dagger', 'Daggers'),
(2, 16, 'Thrown', 'Thrown'),
(2, 17, 'Spear', 'Spears'),
(2, 18, 'Crossbow', 'Crossbows'),
(2, 19, 'Wand', 'Wands'),
(2, 20, 'Fishing Pole', 'Fishing Pole'),
(3, 0, 'Jewelry(OBSOLETE)', ''),
(4, 0, 'Miscellaneous', ''),
(4, 1, 'Cloth', 'Cloth'),
(4, 2, 'Leather', 'Leather'),
(4, 3, 'Mail', 'Mail'),
(4, 4, 'Plate', 'Plate'),
(4, 5, 'Buckler(OBSOLETE)', 'Bucklers'),
(4, 6, 'Shield', 'Shields'),
(4, 7, 'Libram', 'Librams'),
(4, 8, 'Idol', 'Idols'),
(4, 9, 'Totem', 'Totems'),
(5, 0, 'Reagent', ''),
(6, 0, 'Wand(OBSOLETE)', ''),
(6, 1, 'Bolt(OBSOLETE)', ''),
(6, 2, 'Arrow', ''),
(6, 3, 'Bullet', ''),
(6, 4, 'Thrown(OBSOLETE)', ''),
(7, 0, 'Trade Goods', ''),
(7, 1, 'Parts', ''),
(7, 2, 'Explosives', ''),
(7, 3, 'Devices', ''),
(8, 0, 'Generic(OBSOLETE)', ''),
(9, 0, 'Book', ''),
(9, 1, 'Leatherworking', ''),
(9, 2, 'Tailoring', ''),
(9, 3, 'Engineering', ''),
(9, 4, 'Blacksmithing', ''),
(9, 5, 'Cooking', ''),
(9, 6, 'Alchemy', ''),
(9, 7, 'First Aid', ''),
(9, 8, 'Enchanting', ''),
(9, 9, 'Fishing', ''),
(10, 0, 'Money(OBSOLETE)', ''),
(11, 0, 'Quiver(OBSOLETE)', ''),
(11, 1, 'Quiver(OBSOLETE)', ''),
(11, 2, 'Quiver', ''),
(11, 3, 'Ammo Pouch', ''),
(12, 0, 'Quest', ''),
(13, 0, 'Key', ''),
(13, 1, 'Lockpick', ''),
(14, 0, 'Permanent', ''),
(15, 0, 'Junk', '');