DROP TABLE IF EXISTS `lfgdungeons`;

CREATE TABLE `lfgdungeons` (
  `id` mediumint(8) NOT NULL,
  `name` text,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `lfgdungeons`(`id`, `name`) VALUES 
(1, 'Wailing Caverns'),
(2, 'Scholomance'),
(3, 'Ragefire Chasm'),
(5, 'Deadmines'),
(7, 'Shadowfang Keep'),
(9, 'Blackfathom Deeps'),
(11, 'Stormwind Stockades'),
(13, 'Gnomeregan'),
(15, 'Razorfen Kraul'),
(17, 'Scarlet Monastery'),
(19, 'Razorfen Downs'),
(21, 'Uldaman'),
(23, 'Zul\'Farak'),
(25, 'Maraudon'),
(27, 'Sunken Temple'),
(29, 'Blackrock Depths'),
(31, 'Lower Blackrock Spire'),
(33, 'Dire Maul - East'),
(35, 'Dire Maul - West'),
(37, 'Dire Maul - North'),
(39, 'Stratholme'),
(41, 'Zul\'Gurub'),
(43, 'Upper Blackrock Spire'),
(45, 'Onyxia'),
(47, 'Molten Core'),
(49, 'Blackwing Lair'),
(57, 'Elwynn Forest'),
(59, 'Westfall'),
(61, 'Duskwood'),
(63, 'Dun Morogh'),
(65, 'Loch Modan'),
(67, 'Wetlands'),
(69, 'Stranglethorn Vale'),
(71, 'Blasted Lands'),
(73, 'Swamp of Sorrows'),
(75, 'Redridge Mountains'),
(77, 'Burning Steppes'),
(79, 'Searing Gorge'),
(81, 'Badlands'),
(83, 'Arathi Highlands'),
(85, 'Hillsbrad Foothills'),
(87, 'Hinterlands'),
(89, 'Western Plaguelands'),
(91, 'Eastern Plaguelands'),
(93, 'Tirisfal Glades'),
(95, 'Silverpine Forest'),
(97, 'Alterac Mountains'),
(99, 'Durotar'),
(101, 'Mulgore'),
(103, 'The Barrens'),
(105, 'Stonetalon Mountains'),
(107, 'Thousand Needles'),
(109, 'Desolace'),
(111, 'Feralas'),
(113, 'Dustwallow Marsh'),
(115, 'Tanaris'),
(117, 'Un\'goro Crater'),
(119, 'Silithus'),
(121, 'Teldrassil'),
(123, 'Darkshore'),
(125, 'Ashenvale Forest'),
(127, 'Felwood'),
(129, 'Azshara'),
(131, 'Winterspring'),
(51, 'Alterac Valley'),
(53, 'Warsong Gulch'),
(55, 'Arathi Basin');