DROP TABLE IF EXISTS `map`;

CREATE TABLE `map` (
  `entry` mediumint(8) NOT NULL,
  `mapname` text,
  `hordedescription` text,
  `alliancedescription` text,
  PRIMARY KEY (`entry`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `map`(`entry`, `mapname`, `hordedescription`, `alliancedescription`) VALUES 
(0, 'Eastern Kingdoms', '', ''),
(1, 'Kalimdor', '', ''),
(13, 'Testing', '', ''),
(25, 'Scott Test', '', ''),
(29, 'CashTest', '', ''),
(30, 'Alterac Valley', 'Hidden within the Alterac Mountains, Alterac Valley is the home of Thrall?s own clan of orcs, the Frostwolves. The Stormpike dwarves have established a foothold in the valley and seek to plumb its depths for riches, and links to their ancestral past. The territorial Frostwolves, unwilling to suffer the dwarven incursion, have rallied an army... an army eager for righteous slaughter.', 'Hidden within the Alterac Mountains, Alterac Valley is the home of Thrall?s own clan of orcs, the Frostwolves. The Stormpike dwarves have established a foothold in the valley and seek to plumb its depths for riches, and links to their ancestral past. The territorial Frostwolves, unwilling to suffer the dwarven incursion, have rallied an army... an army eager for righteous slaughter.'),
(33, 'Shadowfang Keep', '', ''),
(34, 'Stormwind Stockade', '', ''),
(35, '<unused>StormwindPrison', '', ''),
(36, 'Deadmines', '', ''),
(37, 'Azshara Crater', 'Crush the Alliance!', 'Defend yourself from the onslaught of the Horde!'),
(42, 'Collin\'s Test', '', ''),
(43, 'Wailing Caverns', '', ''),
(44, '<unused> Monastery', '', ''),
(47, 'Razorfen Kraul', '', ''),
(48, 'Blackfathom Deeps', '', ''),
(70, 'Uldaman', '', ''),
(90, 'Gnomeregan', '', ''),
(109, 'Sunken Temple', '', ''),
(129, 'Razorfen Downs', '', ''),
(169, 'Emerald Dream', '', ''),
(189, 'Scarlet Monastery', '', ''),
(209, 'Zul\'Farrak', '', ''),
(229, 'Blackrock Spire', '', ''),
(230, 'Blackrock Depths', '', ''),
(249, 'Onyxia\'s Lair', '', ''),
(269, 'Caverns of Time', '', ''),
(289, 'Scholomance', '', ''),
(309, 'Zul\'Gurub', '', ''),
(329, 'Stratholme', '', ''),
(349, 'Maraudon', '', ''),
(369, 'Deeprun Tram', '', ''),
(389, 'Ragefire Chasm', '', ''),
(409, 'Molten Core', '', ''),
(429, 'Dire Maul', '', ''),
(449, 'Alliance PVP Barracks', '', ''),
(450, 'Horde PVP Barracks', '', ''),
(451, 'Development Land', '', ''),
(469, 'Blackwing Lair', '', ''),
(489, 'Warsong Gulch', 'A valley bordering Ashenvale Forest and the Barrens, Warsong Gulch hosts a constant battle between the Horde and the Alliance. Orcs use their Warsong Mill to cut lumber reaped from Ashenvale, provoking the night elves of Silverwing Hold. Eager to aid their allies, members of every race in Azeroth rush to the Gulch to lend sword, or spell, to the conflict.', 'A valley bordering Ashenvale Forest and the Barrens, Warsong Gulch hosts a constant battle between the Horde and the Alliance. Orcs use their Warsong Mill to cut lumber reaped from Ashenvale, provoking the night elves of Silverwing Hold. Eager to aid their allies, members of every race in Azeroth rush to the Gulch to lend sword, or spell, to the conflict.'),
(509, 'Ruins of Ahn\'Qiraj', '', ''),
(529, 'Arathi Basin', 'The Arathi Basin is one of the main staging points of war between the Humans and the Forsaken in Azeroth. The League of Arathor seek to reclaim lost lands for their benefactors in Stormwind, while the Defilers – elite troopers under the watchful eye of Varimathras – seek to sever the vital connection between the Humans and their Dwarven allies to the south.', 'The Arathi Basin is one of the main staging points of war between the Humans and the Forsaken in Azeroth. The League of Arathor seek to reclaim lost lands for their benefactors in Stormwind, while the Defilers – elite troopers under the watchful eye of Varimathras – seek to sever the vital connection between the Humans and their Dwarven allies to the south.'),
(531, 'Ahn\'Qiraj Temple', '', ''),
(533, 'Naxxramas', '', '');