DROP TABLE IF EXISTS `skillline`;

CREATE TABLE `skillline` (
  `id` mediumint(8) NOT NULL,
  `displayname` text,
  `description` text,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `skillline`(`id`, `displayname`, `description`) VALUES 
(6, 'Frost', ''),
(8, 'Fire', ''),
(26, 'Arms', ''),
(38, 'Combat', ''),
(39, 'Subtlety', ''),
(40, 'Poisons', ''),
(43, 'Swords', 'Higher weapon skill increases your chance to hit.'),
(44, 'Axes', 'Higher weapon skill increases your chance to hit.'),
(45, 'Bows', 'Higher weapon skill increases your chance to hit.'),
(46, 'Guns', 'Higher weapon skill increases your chance to hit.'),
(50, 'Beast Mastery', ''),
(51, 'Survival', ''),
(54, 'Maces', 'Higher weapon skill increases your chance to hit.'),
(55, 'Two-Handed Swords', 'Higher weapon skill increases your chance to hit.'),
(56, 'Holy', ''),
(78, 'Shadow Magic', ''),
(95, 'Defense', 'Higher defense makes you harder to hit and makes monsters less likely to land a crushing blow.'),
(98, 'Language: Common', ''),
(101, 'Dwarven Racial', ''),
(109, 'Language: Orcish', ''),
(111, 'Language: Dwarven', ''),
(113, 'Language: Darnassian', ''),
(115, 'Language: Taurahe', ''),
(118, 'Dual Wield', ''),
(124, 'Tauren Racial', ''),
(125, 'Orc Racial', ''),
(126, 'Night Elf Racial', ''),
(129, 'First Aid', 'Higher first aid skill allows you to learn higher level first aid abilities.  First aid abilities can be found on trainers around the world as well as from quests and as drops from monsters.'),
(134, 'Feral Combat', ''),
(136, 'Staves', 'Higher weapon skill increases your chance to hit.'),
(137, 'Language: Thalassian', ''),
(138, 'Language: Draconic', ''),
(139, 'Language: Demon Tongue', ''),
(140, 'Language: Titan', ''),
(141, 'Language: Old Tongue', ''),
(142, 'Survival', ''),
(148, 'Horse Riding', ''),
(149, 'Wolf Riding', ''),
(150, 'Tiger Riding', ''),
(152, 'Ram Riding', ''),
(155, 'Swimming', ''),
(160, 'Two-Handed Maces', 'Higher weapon skill increases your chance to hit.'),
(162, 'Unarmed', 'Higher skill increases your chance to hit.'),
(163, 'Marksmanship', ''),
(164, 'Blacksmithing', 'Higher smithing skill allows you to learn higher level smithing plans.  Blacksmithing plans can be found on trainers around the world as well as from quests and monsters.'),
(165, 'Leatherworking', 'Higher leatherworking skill allows you to learn higher level leatherworking patterns.  Leatherworking patterns can be found on trainers around the world as well as from quests and monsters.'),
(171, 'Alchemy', 'Higher alchemy skill allows you to learn higher level alchemy recipes.  Alchemy recipes can be found on trainers around the world as well as from quests and monsters.'),
(172, 'Two-Handed Axes', 'Higher weapon skill increases your chance to hit.'),
(173, 'Daggers', 'Higher weapon skill increases your chance to hit.'),
(176, 'Thrown', 'Higher weapon skill increases your chance to hit.'),
(182, 'Herbalism', 'Higher herbalism skill allows you to harvest more difficult herbs around the world.  If you cannot harvest a specific herb, then increase your skill by harvesting easier to gather herbs in lower level areas.'),
(183, 'GENERIC (DND)', ''),
(184, 'Retribution', ''),
(185, 'Cooking', 'Higher cooking skill allows you to learn higher level cooking recipes.  Recipes can be found on trainers around the world as well as from quests and as drops from monsters.'),
(186, 'Mining', 'Higher mining skill allows you to harvest more difficult minerals nodes around the world.  If you cannot harvest a specific mineral, then increase your skill by mining easier to mine minerals in lower level areas.'),
(188, 'Pet - Imp', ''),
(189, 'Pet - Felhunter', ''),
(197, 'Tailoring', 'Higher tailoring skill allows you to learn higher level tailoring patterns.  Tailoring patterns can be found on trainers around the world as well as from quests and monsters.'),
(202, 'Engineering', 'Higher engineering skill allows you to learn higher level engineering schematics.  Schematics can be found on trainers around the world as well as from quests and monsters.'),
(203, 'Pet - Spider', ''),
(204, 'Pet - Voidwalker', ''),
(205, 'Pet - Succubus', ''),
(206, 'Pet - Infernal', ''),
(207, 'Pet - Doomguard', ''),
(208, 'Pet - Wolf', ''),
(209, 'Pet - Cat', ''),
(210, 'Pet - Bear', ''),
(211, 'Pet - Boar', ''),
(212, 'Pet - Crocilisk', ''),
(213, 'Pet - Carrion Bird', ''),
(214, 'Pet - Crab', ''),
(215, 'Pet - Gorilla', ''),
(217, 'Pet - Raptor', ''),
(218, 'Pet - Tallstrider', ''),
(220, 'Racial - Undead', ''),
(226, 'Crossbows', 'Higher weapon skill increases your chance to hit.'),
(228, 'Wands', 'Higher weapon skill increases your chance to hit.'),
(229, 'Polearms', 'Higher weapon skill increases your chance to hit.'),
(236, 'Pet - Scorpid', ''),
(237, 'Arcane', ''),
(251, 'Pet - Turtle', ''),
(253, 'Assassination', ''),
(256, 'Fury', ''),
(257, 'Protection', ''),
(261, 'Beast Training', ''),
(267, 'Protection', ''),
(270, 'Pet - Generic', ''),
(293, 'Plate Mail', 'Allows the wearing of plate armor.'),
(313, 'Language: Gnomish', ''),
(315, 'Language: Troll', ''),
(333, 'Enchanting', 'Higher enchanting skill allows you to learn more powerful formulae.  Formulae can be found on trainers around the world as well as from quests and monsters.'),
(354, 'Demonology', ''),
(355, 'Affliction', ''),
(356, 'Fishing', 'Higher fishing skill increases your chance of catching fish in bodies of water around the world.  If you are having trouble catching fish in a given area, move to a lower level area or purchase a fishing lure and try again.'),
(373, 'Enhancement', ''),
(374, 'Restoration', ''),
(375, 'Elemental Combat', ''),
(393, 'Skinning', 'Higher skinning skill allows you to skin hides from higher level monsters around the world.    Once your skill is above 100, you can divide your skill by 5 to determine the highest level of monster you can skin.'),
(413, 'Mail', 'Allows the wearing of mail armor.'),
(414, 'Leather', 'Allows the wearing of leather armor.'),
(415, 'Cloth', 'Allows the wearing of cloth armor.'),
(433, 'Shield', 'Allows the use of shields.'),
(473, 'Fist Weapons', 'Allows for the use of fist weapons.  Chance to hit is determined by the Unarmed skill.'),
(533, 'Raptor Riding', ''),
(553, 'Mechanostrider Piloting', ''),
(554, 'Undead Horsemanship', ''),
(573, 'Restoration', ''),
(574, 'Balance', ''),
(593, 'Destruction', ''),
(594, 'Holy', ''),
(613, 'Discipline', ''),
(633, 'Lockpicking', ''),
(653, 'Pet - Bat', ''),
(654, 'Pet - Hyena', ''),
(655, 'Pet - Owl', ''),
(656, 'Pet - Wind Serpent', ''),
(673, 'Language: Gutterspeak', ''),
(713, 'Kodo Riding', ''),
(733, 'Racial - Troll', ''),
(753, 'Racial - Gnome', ''),
(754, 'Racial - Human', ''),
(758, 'Pet - Event - Remote Control', ''),
(762, 'Riding', '');