DROP TABLE IF EXISTS `worldsafelocs`;

CREATE TABLE `worldsafelocs` (
  `id` mediumint(8) NOT NULL,
  `areaname` text,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `worldsafelocs`(`id`, `areaname`) VALUES 
(1, 'Stormwind'),
(2, 'Redridge Mountains'),
(3, 'Duskwood, Darkshire'),
(4, 'Westfall, Sentinel Hill'),
(5, 'Dun Morogh'),
(6, 'Loch Modan, Thelsamar'),
(7, 'Wetlands, Crossroads'),
(8, 'Badlands, Graveyard NE '),
(10, 'The Barrens, The Crossroads'),
(31, 'Desolace, Ghost Walker Post'),
(32, 'Durotar, Razor Hill'),
(33, 'Durotar, Orgrimmar'),
(34, 'Mulgore, Red Cloud Mesa'),
(35, 'Darkshore, Auberdine'),
(36, 'Deadwind Pass, Morgan\'s Plot'),
(39, 'Thousand Needles, The Great Lift'),
(49, 'Plains of Snow - Horde Start'),
(70, 'Silithus, Valor\'s Rest'),
(89, 'Mulgore, Bloodhoof Village'),
(90, 'Teldrassil, Darnassus'),
(91, 'Teldrassil, Dolanaar'),
(92, 'Ashenvale, Astranaar'),
(93, 'Teldrassil, Aldrassil'),
(94, 'Tirisfal Glades, Deathknell'),
(96, 'Tirisfal Glades, Undercity'),
(97, 'Silverpine Forest, The Sepulcher'),
(98, 'Hillsbrad Foothills, Tarren Mill'),
(99, 'Arathi Highlands'),
(100, 'Dun Morogh, Anvilmar'),
(101, 'Dun Morogh, Kharanos'),
(102, 'Dun Morogh, Ironforge'),
(103, 'Badlands, Kargath'),
(104, 'Redridge Mountains, Lakeshire'),
(105, 'Elwynn Forest, Northshire'),
(106, 'Elwynn Forest, Goldshire'),
(107, 'Elwynn Forest, Stormwind'),
(108, 'Swamp of Sorrows, Stonard'),
(109, 'Stranglethorn Vale, Booty Bay'),
(129, 'Teldrassil, Rut\'theran Village'),
(149, 'Hillsbrad Foothills, Southshore'),
(169, 'Alterac Valley, Snowfall Graveyard (Mid)'),
(189, 'Dustwallow Marsh, Theramore Isle'),
(209, 'Tanaris, Gadgetzan'),
(229, 'The Barrens, Camp Taurajo'),
(249, 'The Barrens, Ratchet'),
(269, 'Plains of Snow - Alliance Start'),
(289, 'Tirisfal Glades, Brill'),
(309, 'Feralas, Feathermoon Stronghold'),
(310, 'Feralas, Camp Mojache'),
(329, 'Thousand Needles, Shimmering Flats'),
(349, 'The Hinterlands, Aerie Peak'),
(369, 'Azshara, Talrendis Point'),
(370, 'Blasted Lands, Dreadmaul Hold'),
(389, 'Stranglethorn Vale, Northern Stranglethorn'),
(409, 'Stonetalon Mountains, Webwinder Path'),
(429, 'Tirisfal Glades, Faol\'s Rest'),
(449, 'Felwood, Morlos\'Aran'),
(450, 'Un\'Goro Crater, The Marshlands'),
(469, 'Darkshore, Twilight Vale'),
(489, 'Wetlands, Baradin Bay'),
(509, 'Western Plaguelands, Chillwind Camp'),
(510, 'Eastern Plaguelands, Light\'s Hope Chapel'),
(511, 'Winterspring, Everlook'),
(512, 'Ashenvale, Kargathia'),
(529, 'Programmer Isle'),
(549, 'Programmer Isle'),
(569, 'Western Plaguelands, Bulwark'),
(589, 'GM Island'),
(609, 'Azshara, Southridge Beach'),
(610, 'Alterac Valley, Horde Safe'),
(611, 'Alterac Valley, Alliance Safe'),
(629, 'TEST for GM Client Only - Do Not Bug'),
(630, 'Azshara, Legash Encampment'),
(631, 'Dustwallow Marsh, Brackenwall Village'),
(632, 'Burning Steppes, Flame Crest'),
(633, 'Moonglade'),
(634, 'Eastern Plaguelands, Darrowshire'),
(635, 'Felwood, Irontree Woods'),
(636, 'Searing Gorge, Thorium Point'),
(649, 'Durotar, Sen\'jin Village'),
(669, 'Programmer Isle, Bucklers Cemetery 2'),
(670, 'Programmer Isle, Bucklers Cemetery 1'),
(671, 'Programmer Isle, Bucklers Cemetery 3'),
(689, 'Alterac Valley, Stormpike Graveyard (Hi)'),
(690, 'Alterac Valley, Frostwolf Graveyard (Lo)'),
(709, 'Durotar, Valley of Trials'),
(729, 'Alterac Valley, PvP Alliance Choke Graveyard (A-choke)'),
(749, 'Alterac Valley, PvP Horde Choke Graveyard (H-choke)'),
(750, 'Alterac Valley, Frostwolf Relief Hut (H-base)'),
(751, 'Alterac Valley, Stormpike Aid Station (A-base)'),
(769, 'Warsong Gulch - Alliance Enter Loc'),
(770, 'Warsong Gulch - Horde Enter Loc'),
(771, 'Warsong Gulch - Alliance Rez Loc'),
(772, 'Warsong Gulch - Horde Rez Loc'),
(789, 'The Hinterlands, The Overlook Cliffs'),
(809, 'Warsong Gulch - Horde Exit Loc'),
(810, 'Warsong Gulch - Alliance Exit Loc'),
(829, 'Alterac Valley, Alliance Exit'),
(830, 'Alterac Valley, Horde Exit'),
(849, 'Feralas, Dire Maul'),
(850, 'Durotar, Northern Durotar'),
(851, 'Mulgore, Thunder Bluff'),
(852, 'Dun Morogh, Gates of Ironforge'),
(853, 'Tirisfal Glades, Ruins of Lordaeron'),
(854, 'Elwynn Forest, Eastvale Logging Camp'),
(869, 'Western Plaguelands, Caer Darrow'),
(889, 'Arathi Basin - Horde Entrance'),
(890, 'Arathi Basin - Alliance Entrance'),
(891, 'Arathi Basin - Horde Exit'),
(892, 'Arathi Basin - Alliance Exit'),
(893, 'Arathi Basin - Graveyard, H-Mid (Farm)'),
(894, 'Arathi Basin - Graveyard, Mid (Blacksmith)'),
(895, 'Arathi Basin - Graveyard, A-Mid (Stables)'),
(896, 'Arathi Basin - Graveyard, ALT-N (Gold Mine)'),
(897, 'Arathi Basin - Graveyard, ALT-S (Lumber Mill)'),
(898, 'Arathi Basin - Graveyard, A-Base (Trollbane Hall)'),
(899, 'Arathi Basin - Graveyard, H-Base (Defiler\'s Den)'),
(909, 'Eastern Plaguelands, Blackwood Lake'),
(910, 'Silithus, Cenarion Hold'),
(911, 'Duskwood, Ravenhill'),
(913, 'Silithus, Scarab Wall (AQ Only)'),
(927, 'Eastern Plaguelands, Graveyard CG Tower');